import { db } from './db';
import { getTemplate } from '../../templates';
import { ApiResponse, ErrorCodes } from './response';

export interface ProvisionConfig {
  templateId: string;
  includeDemoData?: boolean;
}

export async function provisionTenant(userId: string, config: ProvisionConfig) {
  const template = getTemplate(config.templateId);
  if (!template) {
    throw new Error(`Template ${config.templateId} not found`);
  }

  return await db.withTransaction(async () => {
    // 1. Create tenant using actual schema columns (no template_id column)
    const slug = `${config.templateId}-${Date.now()}`.toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 100);
    const result = await db.query(
      'INSERT INTO tenants (name, slug, industry) VALUES ($1, $2, $3) RETURNING id',
      [`${config.templateId} workspace`, slug, config.templateId]
    );
    const tenantId = result.rows[0]?.id;
    if (!tenantId) throw new Error('Failed to create tenant');

    // 2. Map user to tenant + promote to superadmin (first person = workspace owner)
    await db.query(
      'UPDATE users SET tenant_id = $1, role = $2 WHERE id = $3',
      [tenantId, 'superadmin', userId]
    );

    // 3. Seed demo data if flag is true
    if (config.includeDemoData) {
      // call seed helpers
    }

    return { tenantId };
  });
}

export async function resetDemoData(tenantId: string) {
  // Soft delete all records generated by seed scripts
  await db.queryAsTenant(tenantId, 'UPDATE contacts SET deleted_at = NOW() WHERE is_demo = true');
  await db.queryAsTenant(tenantId, 'UPDATE deals SET deleted_at = NOW() WHERE is_demo = true');
  
  return { success: true, message: 'Demo data cleared' };
}
